### ISSUE TITLE
Issue on installing it !

### ISSUE THREAD

**Issue by afaucogney** [stephanenicolas/loglifecycle#7]
Thank for the lib, this seems to be a required one ! 
However I didn't succeed to runt it.

1/ I get error :
Execution failed for task ':app:transformLogLifeCycleProcessorDebug'.

> Could not execute transformation

2/ In the readme, may I suggest to add :

add this dependency to your plugin.gradle (the project one) file :
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'
        classpath 'com.github.stephanenicolas.loglifecycle:loglifecycle-plugin:1.0.3' 
 }

**Comment by afaucogney** [comment]
@stephanenicolas any hint on this ? I didn't succeed to use your wonderful plugin...

**Comment by stephanenicolas** [comment]
Can you provide more details by running it with gradle -s or -d or both ?

2015-07-30 10:03 GMT-07:00 Faucogney Anthony notifications@github.com:

**Comment by afaucogney** [comment]
@stephanenicolas thanks for answering me.

I'm not used to work with gradle option. So (on a mac) I just start ./gradlew -s -d, and I get tones of logs....

Nothing really understandable for me, seems to be linked to lint and a new module I just added (however is was already not working before I added this module)

Here it is the log  (part where it seems to go wrong):

22:03:49.087 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :CameraModule:assemble UP-TO-DATE
22:03:49.088 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :CameraModule:assemble (Thread[Daemon worker,5,main]) completed. Took 0.004 secs.
22:03:49.088 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :CameraModule:lint (Thread[Daemon worker,5,main]) started.
22:03:49.088 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :CameraModule:lint
22:03:49.089 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':CameraModule:lint'
22:03:49.089 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':CameraModule:lint' is up-to-date
22:03:49.090 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':CameraModule:lint' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
22:03:49.091 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':CameraModule:lint'.
22:03:49.623 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':CameraModule:lint'
22:03:49.623 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :CameraModule:lint FAILED
22:03:49.625 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :CameraModule:lint (Thread[Daemon worker,5,main]) completed. Took 0.537 secs.
22:03:49.625 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker,5,main]] finished, busy: 1.569 secs, idle: 0.067 secs
22:03:49.637 [ERROR] [org.gradle.BuildExceptionReporter] 
22:03:49.644 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
22:03:49.644 [ERROR] [org.gradle.BuildExceptionReporter] 
22:03:49.645 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
22:03:49.645 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':CameraModule:lint'.
22:03:49.646 [ERROR] [org.gradle.BuildExceptionReporter] > class org.objectweb.asm.tree.ClassNode has interface org.objectweb.asm.ClassVisitor as super class
22:03:49.646 [ERROR] [org.gradle.BuildExceptionReporter] 
22:03:49.647 [ERROR] [org.gradle.BuildExceptionReporter] \* Exception is:
22:03:49.648 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':CameraModule:lint'.
22:03:49.649 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
22:03:49.649 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
22:03:49.649 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
22:03:49.650 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
22:03:49.650 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
22:03:49.651 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
22:03:49.651 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
22:03:49.652 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
22:03:49.652 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
22:03:49.653 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
22:03:49.653 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
22:03:49.653 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
22:03:49.654 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
22:03:49.654 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
22:03:49.655 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
22:03:49.655 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
22:03:49.655 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
22:03:49.656 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
22:03:49.656 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
22:03:49.657 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
22:03:49.657 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
22:03:49.658 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
22:03:49.658 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
22:03:49.658 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
22:03:49.659 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
22:03:49.659 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
22:03:49.660 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
22:03:49.660 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
22:03:49.661 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
22:03:49.661 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
22:03:49.661 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
22:03:49.662 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
22:03:49.662 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
22:03:49.663 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
22:03:49.663 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
22:03:49.664 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
22:03:49.664 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
22:03:49.665 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
22:03:49.665 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
22:03:49.665 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
22:03:49.666 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
22:03:49.667 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.Swapper.swap(Swapper.java:38)
22:03:49.667 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
22:03:49.670 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
22:03:49.672 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
22:03:49.673 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
22:03:49.673 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
22:03:49.674 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
22:03:49.675 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
22:03:49.677 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
22:03:49.679 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
22:03:49.680 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
22:03:49.682 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:46)
22:03:49.684 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
22:03:49.684 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
22:03:49.686 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.IncompatibleClassChangeError: class org.objectweb.asm.tree.ClassNode has interface org.objectweb.asm.ClassVisitor as super class
22:03:49.687 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.tasks.Lint$LintGradleIssueRegistry.getIssues(Lint.groovy:257)
22:03:49.688 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.tools.lint.client.api.IssueRegistry.getIssuesForScope(IssueRegistry.java:140)
22:03:49.689 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.tools.lint.client.api.IssueRegistry.createDetectors(IssueRegistry.java:179)
22:03:49.689 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.tools.lint.client.api.LintDriver.computeDetectors(LintDriver.java:607)
22:03:49.690 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:426)
22:03:49.690 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:374)
22:03:49.691 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.tools.lint.LintCliClient.run(LintCliClient.java:129)
22:03:49.691 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.LintGradleClient.run(LintGradleClient.java:112)
22:03:49.692 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.LintGradleClient$run.call(Unknown Source)
22:03:49.692 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.tasks.Lint.runLint(Lint.groovy:198)
22:03:49.693 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.tasks.Lint.this$4$runLint(Lint.groovy)
22:03:49.693 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.tasks.Lint$this$4$runLint$1.callCurrent(Unknown Source)
22:03:49.694 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.tasks.Lint.lintAllVariants(Lint.groovy:89)
22:03:49.694 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.tasks.Lint$lintAllVariants$0.callCurrent(Unknown Source)
22:03:49.695 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.tasks.Lint.lint(Lint.groovy:77)
22:03:49.695 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
22:03:49.696 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
22:03:49.696 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
22:03:49.697 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
22:03:49.697 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
22:03:49.698 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
22:03:49.698 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
22:03:49.698 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
22:03:49.699 [ERROR] [org.gradle.BuildExceptionReporter]        ... 54 more
22:03:49.699 [ERROR] [org.gradle.BuildExceptionReporter] 
22:03:49.699 [LIFECYCLE] [org.gradle.BuildResultLogger] 
22:03:49.700 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
22:03:49.700 [LIFECYCLE] [org.gradle.BuildResultLogger] 
22:03:49.700 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 29.628 secs

**Comment by stephanenicolas** [comment]
Which JDK does your gradle use (gradle -v)

2015-07-30 13:12 GMT-07:00 Faucogney Anthony notifications@github.com:

**Comment by stephanenicolas** [comment]
Also please dump gradle :CameraModule:dependencies

2015-07-30 13:28 GMT-07:00 Stéphane NICOLAS steff.nicolas@gmail.com:

**Comment by afaucogney** [comment]
---

## Gradle 2.2.1

Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_79 (Oracle Corporation 24.79-b02)
OS:           Mac OS X 10.10.4 x86_64

**Comment by stephanenicolas** [comment]
Dump the modules dependencies, there must be someone upgrading asm
dependencies to 4 or something like that

2015-07-30 13:31 GMT-07:00 Faucogney Anthony notifications@github.com:

**Comment by afaucogney** [comment]
Not 100% sur what you mean.

Camera modules has been build correctly.

I typed  "./gradlew :CameraModule:dependencies"

Many things and somes dependencies

+--- com.edmodo:cropper:1.0.1
+--- com.squareup.picasso:picasso:2.2.0
--- com.jakewharton.timber:timber:2.2.2
- long time old warning (at startup)

To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: http://gradle.org/docs/2.2.1/userguide/gradle_daemon.html.
WARNING: Dependency org.apache.httpcomponents:httpclient:4.0.1 is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
WARNING: Dependency org.apache.httpcomponents:httpclient:4.0.1 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages

How do you "dump modules dependencies " ?

**Comment by stephanenicolas** [comment]
dump modules dependencies = ./gradlew :CameraModule:dependencies

Can you just pipe it through 'grep asm' if you don't wanna expose all your
deps here.

2015-07-30 13:38 GMT-07:00 Faucogney Anthony notifications@github.com:

**Comment by afaucogney** [comment]
I got this

```
 |    \--- org.ow2.asm:asm-debug-all:5.0.1
 |    \--- org.ow2.asm:asm-debug-all:5.0.1
```

PS: This is a multi-dex app, do not know of that make interest

**Comment by stephanenicolas** [comment]
Ok, I need to see who makes them in. (give the lines above to see who has
this dep)

2015-07-30 13:56 GMT-07:00 Faucogney Anthony notifications@github.com:

**Comment by afaucogney** [comment]
androidJacocoAnt - The Jacoco ant tasks to use to get execute Gradle tasks.
--- org.jacoco:org.jacoco.ant:0.7.4.201502262128
     +--- org.jacoco:org.jacoco.core:0.7.4.201502262128
     |    --- org.ow2.asm:asm-debug-all:5.0.1
     +--- org.jacoco:org.jacoco.report:0.7.4.201502262128
     |    +--- org.jacoco:org.jacoco.core:0.7.4.201502262128 (*)
     |    --- org.ow2.asm:asm-debug-all:5.0.1
     --- org.jacoco:org.jacoco.agent:0.7.4.201502262128

**Comment by stephanenicolas** [comment]
Ok, do you really mind posting all the output of :<your
module>:dependencies. For all configurations, I can't understand what
happens here.

2015-07-30 14:22 GMT-07:00 Faucogney Anthony notifications@github.com:

**Comment by afaucogney** [comment]
may I email you ?

**Comment by stephanenicolas** [comment]
steff then my familly name at gmail

2015-07-30 14:27 GMT-07:00 Faucogney Anthony notifications@github.com:

**Comment by sirvon** [comment]
resolution?
